# fly.toml app configuration file generated for mini-messageboard-j4nr on 2023-07-20T20:55:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-messageboard-j4nr"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
